defaults:
    - general : general_default
    - model : discrete
    - train : train_default
    - dataset : mutualistic

hydra:
    run:
        dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${general.comment}



